version: '3.8'

services:
  api:
    build:
      context: api
      target: ${API_TARGET}
    env_file:
      - api/.env
    environment:
      - PORT=${CONTAINER_PORT}
    ports:
      - '${HOST_PORT}:${CONTAINER_PORT}'
